site_name: harun      
theme:   
  name: material
  palette:
    primary: red    
  font:
    text: Open Sans
    code: Roboto Mono
  extra:
  alternate:
    - name: English
      link: /en/ 
      lang: en
    - name: Deutsch
      link: /de/
      lang: de
  logo: assets/images/Harun-designstyle-smoothie-m.png
  features:
    - navigation.tabs
    - navigation.instant.prefetch
    - search
    - search.highlight
    - search.suggest

docs_dir: docs 
nav:
  - Home: index.md
  - CV: CV.md
  - About me: about_me.md
  - Projects: Projects.md
  - Cooperation: cooperation.md
  - Research Interest: Research interest.md
  - Methodology: Methodology.md
  - Publications: Publish.md
  - Contact: Contact.md





markdown_extensions:
  - admonition
  - abbr
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - codehilite
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.tabbed
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.smartsymbols
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji 
      emoji_generator: !!python/name:material.extensions.emoji.to_svg



        
